### ISSUE TITLE
add-runbook-links.libsonnet breaks runbook_url from other alerts

### ISSUE THREAD

**Issue by enkov** [povilasv/coredns-mixin#2]
Hello!
I am trying to use this lib with kube-prometheus and when I import alerts like
```
local coreDNSAlerts = (import 'coredns-mixin/mixin.libsonnet').prometheusAlerts;
prometheusAlerts+:: jaegerAlerts + coreDNSAlerts
```
runbook_urls in all other alerts got rewritten 

```
-        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutoffiles
+        runbook_url: https://github.com/povilasv/coredns-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutoffiles
```

**Comment by povilasv** [comment]
Hey, thanks for reporting issue. Feel free to do a Pull Request to fix this :)

**Comment by olegmayko** [comment]
Still doesn't work for me, the runbook url is getting overwritten for runbook defined [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/alerts). It happens because of identical name of this [key](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/4626a8d0dd261dbefa91d9d60cf8bc8240bd053f/alerts/add-runbook-links.libsonnet#L13). @povilasv do you mind if this will be renamed? I can submit PR. Thanks

**Comment by povilasv** [comment]
I see, sure let's do something like `corednsRunbookURLPattern`
